# Generated by Django 3.2 on 2021-06-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='facet',
            field=models.CharField(blank=True, choices=[(None, '----------'), ('identities', 'Self Identity'), ('availability', 'Availability by County'), ('component_categories', 'USDA Meal Component'), ('physical_counties', 'Producer Location: County'), ('delivery_methods', 'Delivery Methods'), ('product_categories', 'Product Categories'), ('product_forms', 'Product details')], default=None, max_length=255, unique=True),
        ),
    ]
