# Generated by Django 3.2.4 on 2021-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_filter_facet'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
