# Generated by Django 3.2.4 on 2021-06-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_filter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='browse_all_button',
            field=models.CharField(default='Show Results', help_text='Text on "get results" button when NO filters are selected.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='browse_filtered_button',
            field=models.CharField(default='Show Filtered Results', help_text='Text on "get results" button when filters are selected.', max_length=255),
        ),
    ]
