# Generated by Django 3.2.4 on 2021-06-29 17:28

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20210629_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='back_button',
            field=models.BooleanField(default=False, help_text="Check to show a 'Back' button at the top of the page", verbose_name='Show back button'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='back_button_text',
            field=models.CharField(default='Back', max_length=255),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='header_blurb',
            field=wagtail.fields.RichTextField(blank=True, default=None, help_text='[Optional] Additional content in header', null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='subtitle',
            field=models.CharField(blank=True, default=None, help_text='[Optional] White label under site header', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.RichTextBlock(blank=True, features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'image', 'embed'], null=True)), ('google_form', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock())], help_text='The URL for the Google form. This will be loaded into a popup when clicked.', label='Google Form Link', template='cms/google_form.html')), ('HTML', wagtail.blocks.RawHTMLBlock(help_text='For fine-tuning very specific/custom blocks.', label='Custom HTML')), ('Embedded_Media', wagtail.embeds.blocks.EmbedBlock(label='Embedded Media'))]),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content_title',
            field=wagtail.fields.RichTextField(blank=True, default='Page Title', null=True),
        ),
    ]
