# Generated by Django 3.2.4 on 2021-06-29 17:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20210629_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultspage',
            name='no_filter_advice',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Try adding filters to narrow your results.</p>', help_text='Advice for users with no filters applied', null=True),
        ),
        migrations.AlterField(
            model_name='resultspage',
            name='filter_advice',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Try removing filters to see more results.</p>', help_text='Helpful advice for users confused by their results', null=True),
        ),
    ]
