# Generated by Django 2.1.7 on 2019-03-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20190312_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('full_name',), 'verbose_name_plural': 'product categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='full_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
