# Generated by Django 3.2 on 2021-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20190313_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('name', 'dateInfoUpdated'), 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AlterModelOptions(
            name='providerproduct',
            options={'ordering': ('category', 'provider'), 'verbose_name': 'supplier product', 'verbose_name_plural': 'supplier products'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='outreachConductor',
            field=models.CharField(blank=True, default=None, help_text='The name of the teammate who reached out to this supplier', max_length=255, null=True, verbose_name='Outreach conducted by'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='productLiabilityInsurance',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Yes', 'Yes'), ('No', 'No')], default='Unknown', max_length=20, verbose_name='This supplier has product liability insurance'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='soldToSchoolsBefore',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Yes', 'Yes'), ('No', 'No')], default='Unknown', max_length=20, verbose_name='This supplier has sold to schools before'),
        ),
    ]
