# Generated by Django 3.2 on 2021-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20210415_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('imageFile', models.ImageField(blank=True, default=None, help_text='Upload a file if one is available (preferred)', null=True, upload_to='')),
                ('imageLink', models.URLField(blank=True, default=None, help_text='Link to viable online image, used if no imageFile is provided', max_length=1000, null=True)),
                ('imageAttribution', models.TextField(blank=True, default=None, null=True)),
                ('usdaLink', models.URLField(blank=True, default=None, help_text='A link to the USDA Food Buying Guide information for this Component Category', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='usdaComponentCategories',
            field=models.ManyToManyField(blank=True, to='providers.ComponentCategory', verbose_name='USDA Component Categories'),
        ),
    ]
