# Generated by Django 3.2 on 2021-05-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20210521_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentcategory',
            options={'ordering': ('order', 'name'), 'verbose_name_plural': 'USDA component categories'},
        ),
        migrations.AddField(
            model_name='componentcategory',
            name='order',
            field=models.IntegerField(default=9),
        ),
    ]
