# Generated by Django 3.2 on 2021-06-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20210611_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addressLine1', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Address Line 1')),
                ('addressLine2', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Address Line 2')),
                ('addressCity', models.CharField(max_length=255, verbose_name='City')),
                ('addressZipCode', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip Code')),
                ('addressState', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schoolAddresses', to='providers.politicalregion', verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='preferredContactMethod',
            field=models.ManyToManyField(blank=True, to='providers.ContactMethod', verbose_name='Preferred contact method'),
        ),
        migrations.AddField(
            model_name='provider',
            name='preferredLanguage',
            field=models.ManyToManyField(blank=True, to='providers.Language', verbose_name='Preferred contact language'),
        ),
        migrations.AddField(
            model_name='provider',
            name='schoolsSoldTo',
            field=models.ManyToManyField(blank=True, to='providers.School', verbose_name='Schools this supplier has done business with before'),
        ),
    ]
