# Generated by Django 3.2 on 2021-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_auto_20210617_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerproduct',
            name='packSize',
            field=models.TextField(blank=True, default=None, help_text='Unit size of orders and other details', null=True, verbose_name='Packaging Info'),
        ),
    ]
